version: '3.8'
services:
  db:
    image: postgres:15
    container_name: digifolio-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: .
    image: digifolio-app:latest
    container_name: digifolio-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?currentSchema=digifolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "12"
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8080:8080"

volumes:
  db_data:
